### ISSUE TITLE
Warning: Each child in a list should have a unique "key" pro

### ISSUE THREAD

**Issue by sntptrck** [hesto2/react-animated-list#1]
![image](https://user-images.githubusercontent.com/25454834/75295243-532d1680-583b-11ea-97eb-c3b2e4cbcb2d.png)
![image](https://user-images.githubusercontent.com/25454834/75295138-1fea8780-583b-11ea-8bc4-491fa2073520.png)
![image](https://user-images.githubusercontent.com/25454834/75295188-37c20b80-583b-11ea-8c5b-6373232428ee.png)

**Comment by hesto2** [comment]
@sntptrck version `0.1.4` has the fix for this. Thanks for reporting the issue! Let me know if you have any other feedback!

**Comment by sntptrck** [comment]
0.1.4 is not avaliable in npm(

**Comment by hesto2** [comment]
Looks like the build got botched, I just re deployed it and have verified that 0.1.4 is now live.
